# 配置从配置中心取，这仅是个配置模板
swagger:
  enabled: true
spring:
  datasource:
    username: bolitao
    password: bolitao
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boliblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # mybatis plus 推荐的 p6spy sql 日志输出，有侵入性，仅在开发测试环境启用
    # driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # url: jdbc:p6spy:mysql://127.0.0.1:3306/boliblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai # 仅在开发环境使用，生产需禁用 mybatis plus log 输出
# mybatis StdOutImpl sql 日志输出，仅在开发测试环境启用
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
bolitao:
  conf:
    secret: thisisatestjwtsecreteyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQthisisatestjwtsecret!
    expire: 604800
    header: Authorization
